# Ensure window index numbers get reordered on delete.
set-option -g renumber-windows on

# Start windows and panes index at 1, not 0.
set -g base-index 1
setw -g pane-base-index 1

# Enable full mouse support.
setw -g mouse

# Split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# Increase history limit
set -g history-limit 10000

# Terminal emulator window title
set -g set-titles on
set -g set-titles-string '[#S:#I.#H] #W'
